//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReadXmlToDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemInterchange
    {
        public long ID { get; set; }
        public string Itemcode { get; set; }
        public string Date { get; set; }
        public string Intref { get; set; }
        public string mesref { get; set; }
    }
}
