//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOOKINFO
    {
        public string BOOKINFO_ID { get; set; }
        public string BOOKINFO_NAME { get; set; }
        public string BOOKINFO_TOTALPAGE { get; set; }
        public string BOOKINFO_FILEPATH { get; set; }
        public string BOOKINFO_AVAR { get; set; }
        public string BOOKINFO_DESC { get; set; }
        public string BOOKINFO_STATUS { get; set; }
        public string BOOKINFO_AUTHOR_ID { get; set; }
        public string BOOKINFO_BOOKTYPE_ID { get; set; }
        public string BOOKINFO_FIELD_ID { get; set; }
        public string BOOKINFO_PUBLISHER_ID { get; set; }
    }
}
