//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOOKTYPE
    {
        public string BOOKTYPE_ID { get; set; }
        public string BOOKTYPE_FULLNAME { get; set; }
        public string BOOKTYPE_NAME { get; set; }
        public string BOOKTYPE_DESC { get; set; }
        public string BOOKTYPE_STATUS { get; set; }
    }
}
