//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOOK_STORE
    {
        public string BOOK_STORE_ID { get; set; }
        public string BOOKINFO_ID { get; set; }
        public int BOOK_STORE_TOTAL { get; set; }
        public int BOOK_STORE_REMAIN { get; set; }
    }
}
