//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOOK
    {
        public string BOOK_ID { get; set; }
        public string BOOK_NAME { get; set; }
        public string BOOK_TOTALPAGE { get; set; }
        public string BOOK_FILEPATH { get; set; }
        public string BOOK_AVAR { get; set; }
        public string BOOK_DESC { get; set; }
        public string BOOK_STATUS { get; set; }
        public string BOOK_AUTHOR_ID { get; set; }
        public string BOOK_BOOKTYPE_ID { get; set; }
        public string BOOK_FIELD_ID { get; set; }
        public string BOOK_PUBLISHER_ID { get; set; }
    
        public virtual AUTHOR AUTHOR { get; set; }
        public virtual BOOKTYPy BOOKTYPy { get; set; }
        public virtual FIELD FIELD { get; set; }
        public virtual PUBLISHER PUBLISHER { get; set; }
    }
}
