//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOOK_INOUT
    {
        public string BOOK_INOUT_ID { get; set; }
        public string BOOKINFO_ID { get; set; }
        public string LIBRARY_CARD_ID { get; set; }
        public string TXTIME { get; set; }
        public string TXDATE { get; set; }
        public string EXDATE { get; set; }
        public string BOOK_INOUT_STATUS { get; set; }
    }
}
