//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIBRARY_EVENT
    {
        public string LIBRARY_EVENT_ID { get; set; }
        public string LIBRARY_EVENT_SUBJECT { get; set; }
        public string LIBRARY_EVENT_ADDRESS { get; set; }
        public string LIBRARY_EVENT_NAME { get; set; }
        public string LIBRARY_EVENT_START { get; set; }
        public string LIBRARY_EVENT_END { get; set; }
        public string LIBRARY_EVENT_DESC { get; set; }
    }
}
