//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LibraryManagementEntities : DbContext
    {
        public LibraryManagementEntities()
            : base("name=LibraryManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ALLCODE> ALLCODEs { get; set; }
        public virtual DbSet<AUTHOR> AUTHORs { get; set; }
        public virtual DbSet<BOOK_INOUT> BOOK_INOUT { get; set; }
        public virtual DbSet<BOOK_STORE> BOOK_STORE { get; set; }
        public virtual DbSet<BOOKINFO> BOOKINFOes { get; set; }
        public virtual DbSet<BOOKINFO_IMG> BOOKINFO_IMG { get; set; }
        public virtual DbSet<BOOKTYPE> BOOKTYPEs { get; set; }
        public virtual DbSet<FIELD> FIELDs { get; set; }
        public virtual DbSet<LIBRARY_CARD> LIBRARY_CARD { get; set; }
        public virtual DbSet<LIBRARY_EVENT> LIBRARY_EVENT { get; set; }
        public virtual DbSet<LIBRARY_EVENT_IMG> LIBRARY_EVENT_IMG { get; set; }
        public virtual DbSet<PUBLISHER> PUBLISHERs { get; set; }
        public virtual DbSet<TLPROFILE> TLPROFILES { get; set; }
    }
}
