//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MENU
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public string URL { get; set; }
        public Nullable<int> DISPLAY_ORDER { get; set; }
        public Nullable<int> GROUP_ID { get; set; }
        public string TARGET { get; set; }
        public bool STATUS { get; set; }
    }
}
