//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PUBLISHER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PUBLISHER()
        {
            this.BOOKS = new HashSet<BOOK>();
        }
    
        public string ID { get; set; }
        public string PUBLISHER_FULLNAME { get; set; }
        public string PUBLISHER_NAME { get; set; }
        public string PUBLISHER_SITE { get; set; }
        public string PUBLISHER_ADDRESS { get; set; }
        public string PUBLISHER_PHONE { get; set; }
        public string PUBLISHER_DESC { get; set; }
        public string PUBLISHER_STATUS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOOK> BOOKS { get; set; }
    }
}
