//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TLPROFILE
    {
        public string ID { get; set; }
        public string NAME { get; set; }
        public string FULLNAME { get; set; }
        public string PIN { get; set; }
        public string DESCRIPTION { get; set; }
        public string TYPE { get; set; }
        public string STATUS { get; set; }
        public string EMAIL { get; set; }
        public string ADDRESS { get; set; }
        public string IDCODE { get; set; }
        public string IDDATE { get; set; }
        public string IDPLACE { get; set; }
        public string MOBILE { get; set; }
        public Nullable<System.Guid> FORGOTCODE { get; set; }
        public string FORGOT_EXPRIED { get; set; }
        public string GENDER { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATED_DATE { get; set; }
        public string UPDATED_BY { get; set; }
    }
}
