//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class VISITOR_STATISTICS
    {
        public System.Guid ID { get; set; }
        public Nullable<System.DateTime> VISITED_DATE { get; set; }
        public string IP_ADDRESS { get; set; }
    }
}
