//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.cfmUatService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="cfmUatService.ServiceSoap")]
    public interface ServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Test", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Test(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PutVendorPaymentToCFM", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool PutVendorPaymentToCFM(string sSystemName, System.Data.DataSet dsReport);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PutReportToCFM", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool PutReportToCFM(string sSystemName, System.Data.DataSet dsReport, int iShif);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PushPaymentToCFM", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool PushPaymentToCFM(string sSystemName, System.Data.DataSet dsReport);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : Test.cfmUatService.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<Test.cfmUatService.ServiceSoap>, Test.cfmUatService.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public string Test(string name) {
            return base.Channel.Test(name);
        }
        
        public bool PutVendorPaymentToCFM(string sSystemName, System.Data.DataSet dsReport) {
            return base.Channel.PutVendorPaymentToCFM(sSystemName, dsReport);
        }
        
        public bool PutReportToCFM(string sSystemName, System.Data.DataSet dsReport, int iShif) {
            return base.Channel.PutReportToCFM(sSystemName, dsReport, iShif);
        }
        
        public bool PushPaymentToCFM(string sSystemName, System.Data.DataSet dsReport) {
            return base.Channel.PushPaymentToCFM(sSystemName, dsReport);
        }
    }
}
